### ISSUE TITLE
dataset labels

### ISSUE THREAD

**Issue by Lycus99** [BCV-Uniandes/TAPIR#1]
Thanks for your excellent work!
I want to know that how to download the labels about the dataset, such as phase label and step label for each frame.

**Comment by Lycus99** [comment]
For /TAPIR/outputs/data_annotations/psi-ava/fold1/annotations/train.csv, I wonder about the meaning of each column. Thanks!

**Comment by nfvalderrama** [comment]
Hi!

To have the labels for each frame is necessary to take the original annotations and extend the phases and steps along the frames during the interval of times that are given in the original file. We have these annotations processed for one frame each second.  We can share these files if that would work for you. 

Regarding the columns in the file train.csv in the annotations folder, they are:

CASE,FRAME,ID_NUMBER,BOX_X1,BOX_Y1,BOX_X2,BOX_Y2,ACTION_1,ACTION_2,ACTION_3,INSTRUMENT,STEP,PHASE

**Comment by Lycus99** [comment]
> Could you please share the annotation files with me? My email address is yc.li@siat.ac.cn
