### ISSUE TITLE
Downloading the PSI-AVA dataset from the link 

### ISSUE THREAD

**Issue by zongyu-zoey-li** [BCV-Uniandes/TAPIR#2]
I was trying to download the data from here http://157.253.243.19/PSI-AVA/ using wget. It told me the connection was refused. Maybe I wasn't doing the right way. Could you tell me how to download the dataset?

**Comment by nfvalderrama** [comment]
Hi!

Thanks for your comment. We are facing some technical problems, but tomorrow the link will be available again, so it can be downloaded using wget.
