### ISSUE TITLE
Atomic action labels

### ISSUE THREAD

**Issue by Lycus99** [BCV-Uniandes/TAPIR#3]
Thanks for your excellent dataset! I have a question about the atomic action labels and beg for your answer. 
As you wrote in the paper, each instrument corresponds to at most 3 atomic actions. I wonder about the relationships between the actions. For example, could I say the actions are _Juxtaposition_ relation？

**Comment by nayobi** [comment]
Hello. We didn't annotate any predefined relationship between actions. For each instrument on each keyframe, we annotated the independent atomic action performed by the instrument regardless of the actions performed by any other instrument.
