### ISSUE TITLE
Download the PSI-AVA dataset

### ISSUE THREAD

**Issue by YujiaLiu310** [BCV-Uniandes/TAPIR#4]
I was trying to download the data from http://157.253.243.19/PSI-AVA/ using wget. It was connected, but after waiting for a while, turned out
"HTTP request sent, awaiting response... Read error (Connection timed out) in headers."
Could you tell me how to download the dataset?

**Comment by nayobi** [comment]
You should be able to download the dataset using wget -r http://157.253.243.19/PSI-AVA/. Please let us know if you still have issues.

**Comment by nayobi** [comment]
Hello, we have modified our download links. You can now download a compressed archive with wget or from the provided Google Drive link. Please check the updated download instructions in the README file and let us know if you are still having trouble.
