### ISSUE TITLE
download link invalid

### ISSUE THREAD

**Issue by lucasestini95** [BCV-Uniandes/TAPIR#5]
Hello, the download [link ](http://157.253.243.19/PSI-AVA/) on the main page is invalid. Could you share the correct download link?
Thanks

**Comment by nayobi** [comment]
Hello. What error are you getting? Maybe you should try downloading the dataset recursively (wget -r).

**Comment by shunliu01** [comment]
It didn't work for me :(  the following code has unchanged for a long time, can yo provide the solution?

wget -r http://157.253.243.19/PSI-AVA/
--2024-05-07 18:50:09--  http://157.253.243.19/PSI-AVA/
Connecting to 157.253.243.19:80... connected.
HTTP request sent, awaiting response...

**Comment by nayobi** [comment]
Hello, we have modified our download links. You can now download a compressed archive with wget or from the provided Google Drive link. Please check the updated download instructions in the README file and let us know if you still have trouble.
